import type { MergedCv } from "./docxCvParser";

const str = (s: string) => JSON.stringify(s ?? "");
const strArr = (a: string[]) => JSON.stringify(a ?? []);

function projectsBlock(list: MergedCv["projects"]): string {
  return (
    "export const projects: Project[] = [\n" +
    list
      .map(
        (p) =>
          `  {\n` +
          `    name: ${str(p.name)},\n` +
          `    description: ${str(p.description)},\n` +
          `    tags: ${strArr(p.tags)},\n` +
          `    link: ${str(p.link)},\n` +
          `    image: ${str(p.image)},\n` +
          `    icon: ${str(p.icon)},\n` +
          `  },`,
      )
      .join("\n") +
    "\n];"
  );
}

function certificatesBlock(list: MergedCv["certificates"]): string {
  return (
    "export const certificates: Certificate[] = [\n" +
    list
      .map(
        (c) =>
          `  {\n` +
          `    name: ${str(c.name)},\n` +
          `    issuer: ${str(c.issuer)},\n` +
          `    year: ${str(c.year)},\n` +
          `    image: ${str(c.image)},\n` +
          `  },`,
      )
      .join("\n") +
    "\n];"
  );
}

function educationBlock(list: MergedCv["education"]): string {
  return (
    "export const education: Education[] = [\n" +
    list
      .map(
        (e) =>
          `  {\n` +
          `    degree: ${str(e.degree)},\n` +
          `    institution: ${str(e.institution)},\n` +
          `    years: ${str(e.years)},\n` +
          `    details: ${str((e as { details?: string }).details || "")},\n` +
          `  },`,
      )
      .join("\n") +
    "\n];"
  );
}

function skillsBlock(list: MergedCv["skills"]): string {
  return (
    "export const skills: Skill[] = [\n" +
    list.map((s) => `  { name: ${str(s.name)}, level: ${s.level} },`).join("\n") +
    "\n];"
  );
}

function personalBlock(p: MergedCv["personal"]): string {
  return `export const personal: Personal = {
  name: ${str(p.name)},
  shortName: ${str(p.shortName)},
  fullName: ${str(p.fullName)},
  role: ${str(p.role)},
  tagline: ${str(p.tagline)},
  summary: ${str(p.summary)},
  email: ${str(p.email)},
  phone: ${str(p.phone)},
  whatsappNumber: ${str(p.whatsappNumber)},
  location: ${str(p.location)},
  website: ${str(p.website)},
  availability: ${str(p.availability)},
  github: ${str(p.github)},
  linkedin: ${str(p.linkedin)},
  instagram: ${str(p.instagram)},
};`;
}

export function generateResumeFile(merged: MergedCv): string {
  const header = `// ⚡  IMPORTED FROM YOUR WORD DOCUMENT — generated by the /import tool.
//  Replace the matching blocks in src/data/resume.ts with these values.
//  Remember: every section of the site + CV + chatbot reads from that file.
//
//  NOTE: the type definitions, quickQuestions and comments at the top of
//  src/data/resume.ts must be kept — only replace the 5 "export const"
//  blocks below.

`;

  return (
    header +
    personalBlock(merged.personal) +
    "\n\n" +
    educationBlock(merged.education) +
    "\n\n" +
    skillsBlock(merged.skills) +
    "\n\n" +
    projectsBlock(merged.projects) +
    "\n\n" +
    certificatesBlock(merged.certificates) +
    "\n"
  );
}